<a href="https://colab.research.google.com/github/MojubaAfo/Machine-learning-/blob/main/Dummy_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import seaborn as sns
from math import sqrt
import scipy.stats as stats
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [54]:
from google.colab import files
uploaded=files.upload()

Saving Book1.xlsx to Book1.xlsx

In [62]:
data =pd.read_excel("Book1.xlsx")

In [63]:
df = pd.DataFrame(data)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1352 entries, 0 to 1351
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Sites       1352 non-null   object
 1   Employees   1352 non-null   object
 2   Industry    1352 non-null   object
 3   Age         1352 non-null   object
 4   Directors   1352 non-null   object
 5   Plan        1352 non-null   object
 6   Account     1352 non-null   object
 7   HR          1352 non-null   object
 8   Enterprise  1352 non-null   object
 9   Artificial  1352 non-null   object
 10  Virtual     1352 non-null   object
 11  Tax         1352 non-null   object
 12  Turnover    1352 non-null   int64
dtypes: int64(1), object(12)
memory usage: 137.4+ KB

In [65]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Turnover,1352.0,2.802119e+06,6.652009e+06,400.0,150000.0,600000.0,2200000.0,71000000.0

In [36]:
Sites = pd.get_dummies(df['Sites'])
Employees = pd.get_dummies(df['Employees'])
Age = pd.get_dummies(df['Age'])
Directors = pd.get_dummies(df['Directors'])
Plan = pd.get_dummies(df['Plan'])
Account = pd.get_dummies(df['Account'])
HR = pd.get_dummies(df['HR'])
Enterprise = pd.get_dummies(df['Enterprise'])
Artificial = pd.get_dummies(df['Artificial'])
Virtual = pd.get_dummies(df['Virtual'])
Tax = pd.get_dummies(df['Tax'])

In [66]:
df = pd.get_dummies(df, columns=['Sites'],prefix='Sites', drop_first=True)
df = pd.get_dummies(df, columns=['Industry'],prefix='Industry', drop_first=True)
df = pd.get_dummies(df, columns=['Employees'], prefix='Employees', drop_first=True)
df = pd.get_dummies(df, columns=['Age'],prefix='Age', drop_first=True)
df = pd.get_dummies(df, columns=['Directors'],prefix='Directors', drop_first=True)
df = pd.get_dummies(df, columns=['Plan'],prefix='Plan', drop_first=True)
df = pd.get_dummies(df, columns=['Account'],prefix='Account', drop_first=True)
df = pd.get_dummies(df, columns=['HR'],prefix='HR', drop_first=True)
df = pd.get_dummies(df, columns=['Enterprise'],prefix='Enterprise', drop_first=True)
df = pd.get_dummies(df, columns=['Artificial'],prefix='Artificial', drop_first=True)
df = pd.get_dummies(df, columns=['Virtual'],prefix='Virtual', drop_first=True)
df = pd.get_dummies(df, columns=['Tax'],prefix='Tax', drop_first=True)

In [67]:
df.head()

,Turnover,Sites_2,Sites_3,Sites_11+,Sites_4-10,Sites_Don't know/ Uncertain,Industry_C - Manufacturing,Industry_F - Construction,Industry_G - Wholesale/ Retail,Industry_H - Transport/ Storage,...,Directors_6-10,Plan_No,Plan_Yes - but not kept up to date,Plan_Yes - kept up to date,Account_Not,HR_Not,Enterprise_Not,Artificial_Not,Virtual_Virtual Reality and Augmented Reality,Tax_Yes
0,40000,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,1,1,1,0,1
1,130000,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,1,0,1,0,0
2,250000,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,1,1,0,1
3,100000,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
4,250000,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,1,1

In [75]:
X=df.drop(columns=['Turnover']).assign(const=1)
X
y=df.Turnover
X
X

,Sites_2,Sites_3,Sites_11+,Sites_4-10,Sites_Don't know/ Uncertain,Industry_C - Manufacturing,Industry_F - Construction,Industry_G - Wholesale/ Retail,Industry_H - Transport/ Storage,Industry_I - Accommodation/ Food,...,Plan_No,Plan_Yes - but not kept up to date,Plan_Yes - kept up to date,Account_Not,HR_Not,Enterprise_Not,Artificial_Not,Virtual_Virtual Reality and Augmented Reality,Tax_Yes,const
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,1,1,0,1,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,1,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,1,1,0,1,1
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1347,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,1,1,0,1,1
1348,0,0,0,0,1,0,0,0,0,0,...,1,0,0,1,1,1,1,0,0,1
1349,0,0,0,0,1,0,0,1,0,0,...,0,1,0,0,1,1,1,0,1,1
1350,0,0,0,0,1,0,0,1,0,0,...,1,0,0,0,1,1,1,0,1,1
1351,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,1,1,0,1,1

In [79]:
model = sm.OLS(y,X)
results = model.fit()
print(results .summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               Turnover   R-squared:                       0.435
Model:                            OLS   Adj. R-squared:                  0.418
Method:                 Least Squares   F-statistic:                     25.22
Date:                Sun, 09 Jul 2023   Prob (F-statistic):          1.77e-133
Time:                        12:31:56   Log-Likelihood:                -22773.
No. Observations:                1352   AIC:                         4.563e+04
Df Residuals:                    1311   BIC:                         4.584e+04
Df Model:                          40
Covariance Type:            nonrobust
=================================================================================================================
                                                    coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------
Sites_2                                        1.179e+06   4.68e+05      2.520      0.012    2.61e+05     2.1e+06
Sites_3                                       -1.443e+06   7.69e+05     -1.877      0.061   -2.95e+06    6.49e+04
Sites_11+                                      1.901e+06   1.45e+06      1.311      0.190   -9.44e+05    4.75e+06
Sites_4-10                                    -1.126e+05   7.64e+05     -0.147      0.883   -1.61e+06    1.39e+06
Sites_Don't know/ Uncertain                   -6.483e+04    2.1e+06     -0.031      0.975   -4.18e+06    4.05e+06
Industry_C - Manufacturing                     4.911e+05   8.37e+05      0.587      0.557   -1.15e+06    2.13e+06
Industry_F - Construction                      4.628e+05   8.77e+05      0.527      0.598   -1.26e+06    2.18e+06
Industry_G - Wholesale/ Retail                 2.029e+06   7.97e+05      2.547      0.011    4.66e+05    3.59e+06
Industry_H - Transport/ Storage                1.551e+06   1.08e+06      1.435      0.151   -5.69e+05    3.67e+06
Industry_I - Accommodation/ Food              -1.459e+06   9.04e+05     -1.613      0.107   -3.23e+06    3.15e+05
Industry_J - Information/ Communication       -4.679e+05   8.97e+05     -0.522      0.602   -2.23e+06    1.29e+06
Industry_KL - Financial/ Real Estate           4.107e+05   9.93e+05      0.413      0.679   -1.54e+06    2.36e+06
Industry_M - Professional/ Scientific         -1.452e+05   8.08e+05     -0.180      0.857   -1.73e+06    1.44e+06
Industry_N - Administrative/ Support           3.834e+05   9.09e+05      0.422      0.673    -1.4e+06    2.17e+06
Industry_P - Education                         -1.23e+06   1.27e+06     -0.967      0.334   -3.73e+06    1.27e+06
Industry_Q - Health/ Social Work               -2.93e+06   9.74e+05     -3.009      0.003   -4.84e+06   -1.02e+06
Industry_R - Arts/ Entertainment               -1.38e+06   1.27e+06     -1.082      0.279   -3.88e+06    1.12e+06
Industry_S - Other service                    -4.211e+05   1.08e+06     -0.391      0.696   -2.53e+06    1.69e+06
Employees_Medium 50 - 249                     -1.328e+07   2.04e+06     -6.517      0.000   -1.73e+07   -9.28e+06
Employees_Micro 1 - 9                         -2.263e+07   2.06e+06    -10.982      0.000   -2.67e+07   -1.86e+07
Employees_No employees                        -2.273e+07   2.09e+06    -10.893      0.000   -2.68e+07   -1.86e+07
Employees_Small 10 - 49                       -2.057e+07   2.05e+06    -10.056      0.000   -2.46e+07   -1.66e+07
Age_11 - 20 years                              1.646e+05    5.6e+05      0.294      0.769   -9.34e+05    1.26e+06
Age_6 - 10 years                              -1.774e+05   5.89e+05     -0.301      0.763   -1.33e+06    9.79e+05
Age_Don't know                                -8.053e+05   5.17e+06     -0.156      0.876    -1.1e+07    9.34e+06
Age_More than 20 years                         2362.9555   5.36e+05      0.004      0.996   -1.05e+06    1.05e+06
Directors_1                                   -9.419e+04   8.85e+05     -0.106      0.915   -1.83e+06    1.64e+06
Directors_2                                    2.187e+05   8.69e+05      0.252      0.801   -1.49e+06    1.92e+06
Directors_11+                                 -5.738e+05   1.49e+06     -0.385      0.700    -3.5e+06    2.35e+06
Directors_3-5                                  1.118e+06    8.8e+05      1.270      0.204   -6.09e+05    2.84e+06
Directors_6-10                                 2.209e+06      1e+06      2.206      0.028    2.44e+05    4.17e+06
Plan_No                                        5.056e+04   1.14e+06      0.044      0.965   -2.18e+06    2.29e+06
Plan_Yes - but not kept up to date            -8.103e+05   1.22e+06     -0.663      0.507   -3.21e+06    1.59e+06
Plan_Yes - kept up to date                    -2.402e+04   1.15e+06     -0.021      0.983   -2.27e+06    2.22e+06
Account_Not                                    9.397e+05   5.57e+05      1.687      0.092   -1.53e+05    2.03e+06
HR_Not                                         -1.05e+06   4.32e+05     -2.429      0.015    -1.9e+06   -2.02e+05
Enterprise_Not                                 -4.31e+06   5.98e+05     -7.207      0.000   -5.48e+06   -3.14e+06
Artificial_Not                                 1.158e+06   7.83e+05      1.478      0.140   -3.79e+05    2.69e+06
Virtual_Virtual Reality and Augmented Reality  7.041e+05   1.13e+06      0.621      0.535   -1.52e+06    2.93e+06
Tax_Yes                                        7.195e+05   6.51e+05      1.104      0.270   -5.58e+05       2e+06
const                                          2.577e+07   2.85e+06      9.059      0.000    2.02e+07    3.14e+07
==============================================================================
Omnibus:                     1397.501   Durbin-Watson:                   1.849
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           117994.704
Skew:                           4.819   Prob(JB):                         0.00
Kurtosis:                      47.740   Cond. No.                         91.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [53]:
import numpy as np
from google.colab import autoviz
df_7807384955877902947 = autoviz.get_registered_df('df_7807384955877902947')

def categorical_histogram(df, colname, figsize=(2, 1.2), mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  _, ax = plt.subplots(figsize=figsize)
  bars = df[colname].value_counts()
  plt.barh(bars.index, bars.values, color=sns.palettes.mpl_palette(mpl_palette_name))
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(df_7807384955877902947, *['Age'], **{})
chart

In [29]:
X = pd.concat([df['Turnover'], Sites, Employees, Age, Directors, Plan, Account, HR, Enterprise, Artificial, Virtual, Tax], axis=1)

In [31]:
X

,Turnover,Employees,Industry,Age,Directors,Plan,Account,HR,Enterprise,Artificial,...,Age,Directors,Plan,Account,HR,Enterprise,Artificial,Virtual,Turnover,Tax_Yes
0,40000,No employees,ABDE - Primary,0 - 5 years,1,Yes - but not kept up to date,Accountancy software,Not,Not,Not,...,0 - 5 years,1,Yes - but not kept up to date,Accountancy software,Not,Not,Not,Not,40000,1
1,130000,No employees,ABDE - Primary,11 - 20 years,3-5,Yes - kept up to date,Not,Not,Enterprise Resource Planning (ERP) software,Not,...,11 - 20 years,3-5,Yes - kept up to date,Not,Not,Enterprise Resource Planning (ERP) software,Not,Not,130000,0
2,250000,No employees,ABDE - Primary,More than 20 years,2,No,Accountancy software,Not,Not,Not,...,More than 20 years,2,No,Accountancy software,Not,Not,Not,Not,250000,1
3,100000,No employees,ABDE - Primary,More than 20 years,2,No,Accountancy software,Not,Enterprise Resource Planning (ERP) software,"Artificial Intelligence, Robotics or Automation",...,More than 20 years,2,No,Accountancy software,Not,Enterprise Resource Planning (ERP) software,"Artificial Intelligence, Robotics or Automation",Not,100000,1
4,250000,No employees,ABDE - Primary,More than 20 years,3-5,Yes - kept up to date,Accountancy software,HR management software,Not,"Artificial Intelligence, Robotics or Automation",...,More than 20 years,3-5,Yes - kept up to date,Accountancy software,HR management software,Not,"Artificial Intelligence, Robotics or Automation",Virtual Reality and Augmented Reality,250000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1347,100000,No employees,M - Professional/ Scientific,6 - 10 years,2,Yes - kept up to date,Accountancy software,Not,Not,Not,...,6 - 10 years,2,Yes - kept up to date,Accountancy software,Not,Not,Not,Not,100000,1
1348,12000,No employees,S - Other service,0 - 5 years,1,No,Not,Not,Not,Not,...,0 - 5 years,1,No,Not,Not,Not,Not,Not,12000,0
1349,450000,Micro 1 - 9,G - Wholesale/ Retail,0 - 5 years,2,Yes - but not kept up to date,Accountancy software,Not,Not,Not,...,0 - 5 years,2,Yes - but not kept up to date,Accountancy software,Not,Not,Not,Not,450000,1
1350,15000,Micro 1 - 9,G - Wholesale/ Retail,More than 20 years,1,No,Accountancy software,Not,Not,Not,...,More than 20 years,1,No,Accountancy software,Not,Not,Not,Not,15000,1
1351,600000,Micro 1 - 9,M - Professional/ Scientific,More than 20 years,2,Yes - kept up to date,Accountancy software,Not,Not,Not,...,More than 20 years,2,Yes - kept up to date,Accountancy software,Not,Not,Not,Not,600000,1

In [25]:
df

,Sites,Employees,Industry,Age,Directors,Plan,Account,HR,Enterprise,Artificial,Virtual,Tax,Turnover
0,1,No employees,ABDE - Primary,0 - 5 years,1,Yes - but not kept up to date,Accountancy software,Not,Not,Not,Not,Yes,40000
1,1,No employees,ABDE - Primary,11 - 20 years,3-5,Yes - kept up to date,Not,Not,Enterprise Resource Planning (ERP) software,Not,Not,No,130000
2,1,No employees,ABDE - Primary,More than 20 years,2,No,Accountancy software,Not,Not,Not,Not,Yes,250000
3,1,No employees,ABDE - Primary,More than 20 years,2,No,Accountancy software,Not,Enterprise Resource Planning (ERP) software,"Artificial Intelligence, Robotics or Automation",Not,Yes,100000
4,1,No employees,ABDE - Primary,More than 20 years,3-5,Yes - kept up to date,Accountancy software,HR management software,Not,"Artificial Intelligence, Robotics or Automation",Virtual Reality and Augmented Reality,Yes,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1347,Don't know/ Uncertain,No employees,M - Professional/ Scientific,6 - 10 years,2,Yes - kept up to date,Accountancy software,Not,Not,Not,Not,Yes,100000
1348,Don't know/ Uncertain,No employees,S - Other service,0 - 5 years,1,No,Not,Not,Not,Not,Not,No,12000
1349,Don't know/ Uncertain,Micro 1 - 9,G - Wholesale/ Retail,0 - 5 years,2,Yes - but not kept up to date,Accountancy software,Not,Not,Not,Not,Yes,450000
1350,Don't know/ Uncertain,Micro 1 - 9,G - Wholesale/ Retail,More than 20 years,1,No,Accountancy software,Not,Not,Not,Not,Yes,15000
1351,Don't know/ Uncertain,Micro 1 - 9,M - Professional/ Scientific,More than 20 years,2,Yes - kept up to date,Accountancy software,Not,Not,Not,Not,Yes,600000

In [20]:
X.describe()
print(X.dtypes)

Turnover                        int64
Employees                      object
Industry                       object
Age                            object
Directors                      object
Plan                           object
Account                        object
HR                             object
Enterprise                     object
Artificial                     object
Virtual                        object
Tax                            object
Turnover                        int64
Sites_11+                       uint8
Sites_2                         uint8
Sites_3                         uint8
Sites_4-10                      uint8
Sites_Don't know/ Uncertain     uint8
dtype: object